### ISSUE TITLE
Neuropixel data used in rastermap(gui)

### ISSUE THREAD

**Issue by gersgers** [MouseLand/rastermap#27]
I would like to use rastermap on neuropixel data. The data are detected and sorted using Kilosort 2.5 and Phy. I further analyze the data with Matlab.
I have seen in your publications that rastermap can be applied to such data. However, the pipeline and necessary data layout is not clear to me.
Can you provide me with information on this?
Best,
Stefan

**Comment by jbwallace123** [comment]
Hi @gersgers, did you ever figure out a solution to this issue? I have attempted feeding in npx data as spikes binned (neuron x time -- e.g. histogram counts) and as neurons x spiketimes but did not have success. I am not using the GUI but attempting via jupyter/cli first. Any luck on your end?

**Comment by carsen-stringer** [comment]
can you please post the error message? we have an example notebook here using a neuron by time matrix (binned from spike times): https://github.com/MouseLand/rastermap/blob/main/notebooks/rastermap_singleneurons.ipynb

**Comment by carsen-stringer** [comment]
Ah no, the zeros should be kept in. Those are bins where the neurons don't spike and that's useful info for making the visualization. The sparsity is fine, it should also be able to handle neurons without any spikes, but let me know if you get an error there.

Instead of downsampling, you should bin so that you retain all the spikes. If you have a list of spike times and cluster ids (st and clu), this can be done with this command here: https://github.com/MouseLand/rastermap/blob/0a283fe117c55a89278a3f35e6d761efe8c9bff3/paper/loaders.py#L137

We will integrate this in as a data loader, I'll put an enhancement tag on it.

**Comment by jbwallace123** [comment]
Got it! That worked! I was able to run it and successfully produce the raster. 
There were some dtype issues based on querying from the database. But going from object --> float64 fixed the issue. 

Thank you!

**Comment by carsen-stringer** [comment]
this is now added!
